import { CardTemplate } from '../types';

export const CARD_TEMPLATES: CardTemplate[] = [
  {
    id: 'tu_central',
    name: 'TU Central Campus Classic',
    badge: 'Official Standard',
    description: 'Authentic Tribhuvan University Kirtipur layout with deep royal blue headers, gold seal accents, and dual verification lines.',
    instituteName: 'TRIBHUVAN UNIVERSITY',
    nativeName: 'त्रिभुवन विश्वविद्यालय',
    campusSubTitle: 'Central Campus, Kirtipur, Kathmandu, Nepal',
    librarySubTitle: 'Central Library, Kirtipur Complex',
    program: 'B.Sc. Computer Science & IT (B.Sc. CSIT)',
    department: 'Central Dept. of Computer Science & IT',
    faculty: 'Institute of Science & Technology',
    establishedText: 'Estd. 1959 A.D. (2016 B.S.)',
    studentCardTheme: {
      primaryColor: '#1e3a8a',
      secondaryColor: '#dc2626',
      borderAccent: '#fbbf24',
      badgeBg: '#1e3a8a',
      badgeText: '#ffffff',
    },
    libraryCardTheme: {
      primaryColor: '#831843',
      secondaryColor: '#9f1239',
      borderAccent: '#f59e0b',
      badgeBg: '#831843',
      badgeText: '#ffffff',
    },
    defaultCard1Type: 'student',
    defaultCard2Type: 'library',
  },
  {
    id: 'tu_iost',
    name: 'TU IOST Science & Tech',
    badge: 'Faculty Standard',
    description: 'Institute of Science and Technology modern design with vibrant cyan accent and digital barcode integration.',
    instituteName: 'INSTITUTE OF SCIENCE & TECHNOLOGY',
    nativeName: 'विज्ञान तथा प्रविधि अध्ययन संस्थान',
    campusSubTitle: 'Dean Office, Kirtipur, Kathmandu',
    librarySubTitle: 'IOST Research Library & Resource Centre',
    program: 'B.Sc. Computer Science & IT',
    department: 'Department of Computer Science',
    faculty: 'Institute of Science and Technology',
    establishedText: 'Estd. 1973 A.D.',
    studentCardTheme: {
      primaryColor: '#0369a1',
      secondaryColor: '#0284c7',
      borderAccent: '#38bdf8',
      badgeBg: '#0369a1',
      badgeText: '#ffffff',
    },
    libraryCardTheme: {
      primaryColor: '#0f766e',
      secondaryColor: '#14b8a6',
      borderAccent: '#2dd4bf',
      badgeBg: '#0f766e',
      badgeText: '#ffffff',
    },
    defaultCard1Type: 'student',
    defaultCard2Type: 'library',
  },
  {
    id: 'tu_ioe',
    name: 'IOE Engineering Campus',
    badge: 'Pulchowk / IOE',
    description: 'High-contrast engineering badge with technical emerald styling, campus accreditation code, and laboratory gate clearance.',
    instituteName: 'PULCHOWK CAMPUS, IOE',
    nativeName: 'पुल्चोक क्याम्पस, इन्जिनियरिङ अध्ययन संस्थान',
    campusSubTitle: 'Institute of Engineering, Lalitpur',
    librarySubTitle: 'Pulchowk Central Engineering Library',
    program: 'B.E. Computer Engineering',
    department: 'Dept. of Electronics & Computer Eng.',
    faculty: 'Institute of Engineering (IOE)',
    establishedText: 'Estd. 1972 A.D.',
    studentCardTheme: {
      primaryColor: '#065f46',
      secondaryColor: '#047857',
      borderAccent: '#34d399',
      badgeBg: '#065f46',
      badgeText: '#ffffff',
    },
    libraryCardTheme: {
      primaryColor: '#312e81',
      secondaryColor: '#4338ca',
      borderAccent: '#818cf8',
      badgeBg: '#312e81',
      badgeText: '#ffffff',
    },
    defaultCard1Type: 'student',
    defaultCard2Type: 'library',
  },
  {
    id: 'tu_modern',
    name: 'Modern Contemporary Minimal',
    badge: 'Modern UI',
    description: 'Ultra-sleek corporate academic styling with crisp sans-serif headers, floating QR code, and micro-grid security watermark.',
    instituteName: 'TRIBHUVAN UNIVERSITY',
    nativeName: 'त्रिभुवन विश्वविद्यालय',
    campusSubTitle: 'Higher Education Board, Kathmandu, Nepal',
    librarySubTitle: 'Digital Academic Resource Centre',
    program: 'Master of Information Technology (MIT)',
    department: 'Faculty of Science & Technology',
    faculty: 'Graduate Studies Board',
    establishedText: 'Estd. 1959 A.D.',
    studentCardTheme: {
      primaryColor: '#0f172a',
      secondaryColor: '#334155',
      borderAccent: '#64748b',
      badgeBg: '#0f172a',
      badgeText: '#ffffff',
    },
    libraryCardTheme: {
      primaryColor: '#1e293b',
      secondaryColor: '#475569',
      borderAccent: '#94a3b8',
      badgeBg: '#1e293b',
      badgeText: '#ffffff',
    },
    defaultCard1Type: 'student',
    defaultCard2Type: 'library',
  },
  {
    id: 'tu_trichandra',
    name: 'Tri-Chandra Historic College',
    badge: 'Pioneer College',
    description: 'Heritage crimson and deep copper badge honoring Nepal oldest premier higher education institution at Ghantaghar.',
    instituteName: 'TRI-CHANDRA MULTIPLE CAMPUS',
    nativeName: 'त्रि-चन्द्र बहुमुखी क्याम्पस',
    campusSubTitle: 'Ghantaghar, Kathmandu, Nepal',
    librarySubTitle: 'Tri-Chandra Heritage Library',
    program: 'B.Sc. Geology & Environment',
    department: 'Department of Geology',
    faculty: 'Faculty of Science',
    establishedText: 'Estd. 1918 A.D. (1975 B.S.)',
    studentCardTheme: {
      primaryColor: '#7c2d12',
      secondaryColor: '#9a3412',
      borderAccent: '#fbbf24',
      badgeBg: '#7c2d12',
      badgeText: '#ffffff',
    },
    libraryCardTheme: {
      primaryColor: '#701a75',
      secondaryColor: '#86198f',
      borderAccent: '#f472b6',
      badgeBg: '#701a75',
      badgeText: '#ffffff',
    },
    defaultCard1Type: 'student',
    defaultCard2Type: 'library',
  },
  {
    id: 'work_employment_id',
    name: 'Corporate & University Staff ID',
    badge: 'Faculty / Staff',
    description: 'Professional employment badge with corporate security clearances, supervisor signature, and smart chip RFID simulation.',
    instituteName: 'TRIBHUVAN UNIVERSITY ADMINISTRATION',
    nativeName: 'त्रिभुवन विश्वविद्यालय केन्द्रीय कार्यालय',
    campusSubTitle: 'Central Administrative Secretariat, Kirtipur',
    librarySubTitle: 'Faculty Reference Archives',
    program: 'Faculty / Administrative Service',
    department: 'Department of Information Systems',
    faculty: 'University Central Administration',
    establishedText: 'Estd. 1959 A.D.',
    studentCardTheme: {
      primaryColor: '#1e293b',
      secondaryColor: '#0284c7',
      borderAccent: '#38bdf8',
      badgeBg: '#0f172a',
      badgeText: '#ffffff',
    },
    libraryCardTheme: {
      primaryColor: '#1e3a8a',
      secondaryColor: '#2563eb',
      borderAccent: '#60a5fa',
      badgeBg: '#1e3a8a',
      badgeText: '#ffffff',
    },
    workCardTheme: {
      primaryColor: '#1e293b',
      secondaryColor: '#0284c7',
      borderAccent: '#38bdf8',
      badgeBg: '#0f172a',
      badgeText: '#ffffff',
    },
    defaultCard1Type: 'work',
    defaultCard2Type: 'library',
  },
  {
    id: 'loyalty_vip',
    name: 'Club VIP & Elite Loyalty Card',
    badge: 'VIP Membership',
    description: 'High-tier metallic gold and obsidian privilege card with holographic seal, embossed numbering, and barcode scan.',
    instituteName: 'TU ALUMNI & SCHOLARS CLUB',
    nativeName: 'त्रिभुवन विश्वविद्यालय पूर्वविद्यार्थी समाज',
    campusSubTitle: 'Global Alumni & Academic Association',
    librarySubTitle: 'Scholars Circle Resource Lounge',
    program: 'Lifetime Academic Member',
    department: 'University Relations & Development',
    faculty: 'Alumni Association',
    establishedText: 'Estd. 1959 A.D.',
    studentCardTheme: {
      primaryColor: '#78350f',
      secondaryColor: '#b45309',
      borderAccent: '#fde68a',
      badgeBg: '#78350f',
      badgeText: '#fef3c7',
    },
    libraryCardTheme: {
      primaryColor: '#18181b',
      secondaryColor: '#27272a',
      borderAccent: '#d4d4d8',
      badgeBg: '#18181b',
      badgeText: '#ffffff',
    },
    loyaltyCardTheme: {
      primaryColor: '#78350f',
      secondaryColor: '#b45309',
      borderAccent: '#fde68a',
      badgeBg: '#78350f',
      badgeText: '#fef3c7',
    },
    defaultCard1Type: 'student',
    defaultCard2Type: 'loyalty',
  },
];
