import { CanvasElement } from '../types/canvas';
import { StudentDetails, InstituteConfig, SignatureConfig } from '../types';

export function createDefaultCanvasElements(
  studentDetails: StudentDetails,
  instituteConfig: InstituteConfig,
  signatureConfig: SignatureConfig,
  photoUrl: string
): CanvasElement[] {
  return [
    {
      id: 'elem-bg-header',
      type: 'shape',
      name: 'Top Header Bar',
      x: 0,
      y: 0,
      width: 420,
      height: 48,
      rotation: 0,
      zIndex: 1,
      isLocked: false,
      isHidden: false,
      content: 'Header Accent',
      style: {
        backgroundColor: '#1e3a8a',
        borderRadius: 0,
        opacity: 0.95,
      },
    },
    {
      id: 'elem-institute-native',
      type: 'text',
      name: 'Institute Devanagari Name',
      x: 12,
      y: 6,
      width: 396,
      height: 18,
      rotation: 0,
      zIndex: 2,
      isLocked: false,
      isHidden: false,
      content: instituteConfig.nativeName || 'त्रिभुवन विश्वविद्यालय',
      style: {
        color: '#fef08a',
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
        fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
      },
    },
    {
      id: 'elem-institute-name',
      type: 'text',
      name: 'Institute Title',
      x: 12,
      y: 22,
      width: 396,
      height: 22,
      rotation: 0,
      zIndex: 3,
      isLocked: false,
      isHidden: false,
      content: instituteConfig.name || 'TRIBHUVAN UNIVERSITY',
      style: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '800',
        textAlign: 'center',
        letterSpacing: '0.05em',
        fontFamily: "'Cinzel', serif",
      },
    },
    {
      id: 'elem-photo',
      type: 'image',
      name: 'Passport Photo',
      x: 16,
      y: 58,
      width: 96,
      height: 122,
      rotation: 0,
      zIndex: 4,
      isLocked: false,
      isHidden: false,
      content: photoUrl,
      style: {
        borderRadius: 6,
        borderColor: '#1e3a8a',
        borderWidth: 2,
        borderStyle: 'solid',
        objectFit: 'cover',
      },
    },
    {
      id: 'elem-card-title',
      type: 'badge',
      name: 'Card Title Badge',
      x: 122,
      y: 54,
      width: 278,
      height: 22,
      rotation: 0,
      zIndex: 5,
      isLocked: false,
      isHidden: false,
      content: 'STUDENT IDENTITY CARD',
      style: {
        backgroundColor: '#dbeafe',
        color: '#1e40af',
        fontSize: 10,
        fontWeight: 'bold',
        textAlign: 'center',
        borderRadius: 4,
        letterSpacing: '0.08em',
      },
    },
    {
      id: 'elem-student-name',
      type: 'text',
      name: 'Student Name',
      x: 122,
      y: 80,
      width: 280,
      height: 24,
      rotation: 0,
      zIndex: 6,
      isLocked: false,
      isHidden: false,
      content: studentDetails.name || 'Isabella Rose',
      style: {
        color: '#0f172a',
        fontSize: 16,
        fontWeight: '800',
        textAlign: 'left',
        fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
      },
    },
    {
      id: 'elem-program',
      type: 'text',
      name: 'Program & Degree',
      x: 122,
      y: 106,
      width: 280,
      height: 20,
      rotation: 0,
      zIndex: 7,
      isLocked: false,
      isHidden: false,
      content: `Program: ${studentDetails.program || 'B.Sc. CSIT'}`,
      style: {
        color: '#334155',
        fontSize: 11,
        fontWeight: '600',
        textAlign: 'left',
      },
    },
    {
      id: 'elem-roll-id',
      type: 'text',
      name: 'Roll & ID Number',
      x: 122,
      y: 128,
      width: 280,
      height: 20,
      rotation: 0,
      zIndex: 8,
      isLocked: false,
      isHidden: false,
      content: `Roll No: ${studentDetails.rollNo || '167'} • ID: ${studentDetails.idNumber || 'TU-2022-0167'}`,
      style: {
        color: '#475569',
        fontSize: 11,
        fontWeight: 'bold',
        fontFamily: "'Space Mono', monospace",
        textAlign: 'left',
      },
    },
    {
      id: 'elem-validity',
      type: 'text',
      name: 'Validity & Issue Dates',
      x: 122,
      y: 150,
      width: 280,
      height: 18,
      rotation: 0,
      zIndex: 9,
      isLocked: false,
      isHidden: false,
      content: `Date of Issue: ${studentDetails.issueDate || '2022 Dec 01'} • Valid Until: ${studentDetails.validUntil || '2026 Nov 30'}`,
      style: {
        color: '#475569',
        fontSize: 9.5,
        fontWeight: '700',
        textAlign: 'left',
      },
    },
    {
      id: 'elem-student-sign',
      type: 'signature',
      name: 'Holder Signature',
      x: 16,
      y: 196,
      width: 96,
      height: 32,
      rotation: 0,
      zIndex: 10,
      isLocked: false,
      isHidden: false,
      content: signatureConfig.studentSignatureText || 'Isabella R.',
      style: {
        color: '#1e3a8a',
        fontSize: 18,
        fontFamily: "'Great Vibes', cursive",
        textAlign: 'center',
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: '#94a3b8',
      },
    },
    {
      id: 'elem-authority-sign',
      type: 'signature',
      name: 'Authorized Signatory',
      x: 290,
      y: 188,
      width: 115,
      height: 40,
      rotation: 0,
      zIndex: 11,
      isLocked: false,
      isHidden: false,
      content: signatureConfig.authoritySignatureName || 'Campus Chief',
      style: {
        color: '#0f172a',
        fontSize: 11,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    },
    {
      id: 'elem-gold-seal',
      type: 'badge',
      name: 'Official Hologram Seal',
      x: 220,
      y: 178,
      width: 52,
      height: 52,
      rotation: 0,
      zIndex: 12,
      isLocked: false,
      isHidden: false,
      content: 'SEAL',
      style: {
        backgroundColor: '#fef3c7',
        color: '#b45309',
        borderColor: '#d97706',
        borderWidth: 2,
        borderRadius: 26,
        fontSize: 9,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    },
  ];
}

export function createNewElement(
  type: CanvasElement['type'],
  existingCount: number,
  defaultPhoto?: string
): CanvasElement {
  const id = `elem-${type}-${Date.now()}`;
  const zIndex = existingCount + 1;

  switch (type) {
    case 'text':
      return {
        id,
        type: 'text',
        name: `Text Layer ${existingCount + 1}`,
        x: 60,
        y: 80,
        width: 160,
        height: 28,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: 'Custom Text Here',
        style: {
          color: '#0f172a',
          fontSize: 14,
          fontWeight: 'bold',
          textAlign: 'left',
          fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
        },
      };
    case 'shape':
      return {
        id,
        type: 'shape',
        name: `Shape Layer ${existingCount + 1}`,
        x: 60,
        y: 90,
        width: 120,
        height: 45,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: '',
        style: {
          backgroundColor: '#3b82f6',
          borderRadius: 8,
          borderColor: '#1d4ed8',
          borderWidth: 1,
          opacity: 0.9,
        },
      };
    case 'badge':
      return {
        id,
        type: 'badge',
        name: `Badge Layer ${existingCount + 1}`,
        x: 80,
        y: 80,
        width: 140,
        height: 26,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: 'OFFICIAL BADGE',
        style: {
          backgroundColor: '#fef08a',
          color: '#854d0e',
          fontSize: 10,
          fontWeight: 'bold',
          textAlign: 'center',
          borderRadius: 13,
          letterSpacing: '0.05em',
        },
      };
    case 'image':
      return {
        id,
        type: 'image',
        name: `Image Layer ${existingCount + 1}`,
        x: 80,
        y: 60,
        width: 90,
        height: 110,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: defaultPhoto || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&fit=crop&q=80',
        style: {
          borderRadius: 6,
          borderColor: '#2563eb',
          borderWidth: 2,
          borderStyle: 'solid',
          objectFit: 'cover',
        },
      };
    case 'signature':
      return {
        id,
        type: 'signature',
        name: `Signature Layer ${existingCount + 1}`,
        x: 80,
        y: 160,
        width: 120,
        height: 36,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: 'Authorized Sign',
        style: {
          color: '#1e3a8a',
          fontSize: 20,
          fontFamily: "'Great Vibes', cursive",
          textAlign: 'center',
        },
      };
    case 'barcode':
      return {
        id,
        type: 'barcode',
        name: `Barcode Block ${existingCount + 1}`,
        x: 80,
        y: 180,
        width: 180,
        height: 38,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: 'TU-2022-0167',
        style: {
          backgroundColor: '#ffffff',
          color: '#000000',
          borderRadius: 4,
          padding: 4,
        },
      };
    default:
      return {
        id,
        type: 'text',
        name: `Layer ${existingCount + 1}`,
        x: 50,
        y: 50,
        width: 100,
        height: 30,
        rotation: 0,
        zIndex,
        isLocked: false,
        isHidden: false,
        content: 'New Element',
        style: {},
      };
  }
}
